### ISSUE TITLE
BPF_MAP_TYPE_PROG_ARRAY permits circular references

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1509]
Programs stored in a BPF_MAP_TYPE_PROG_ARRAY can hold a reference to the map they are inserted in.

This results in programs that don't get cleaned when the loading program crashes.

**Comment by dahavey** [comment]
@saxena-anurag, please add repo details.

**Comment by saxena-anurag** [comment]
PROG_ARRAY_MAP currently by design allows circular references. This caused issues in case of nested tail calls. Issue #671 provides repro details. 

I had made some changes in PR #680 to allow clearing of prog array map from user mode, so that the circular reference can be broken, but in low memory conditions (or due some other issue), if the user mode app exits before clearing the prog array map, then both the map and program do not get unloaded.

**Comment by dthaler** [comment]
@dv-msft Can you create the test cases we discussed?

**Comment by dv-msft** [comment]
This fix will require at least two new test cases. Specifically:

1. A test case with a 'direct' circular reference. For example, ```program1 -> some_map -> program1```. While these results *can* be indirectly obtained via one of the existing test cases, it would be worthwhile to implement this one as a standalone test case of the **MUSTFAIL** type.
2. A test case with an 'indirect' circular reference(s).  For example, ```program1 -> some_map -> another_map -> ... -> program1```.  This is a new test case and also needs of the **MUSTFAIL** type.
