### ISSUE TITLE
ebpf_program_load fails to check bpf_object__next_program

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#1633]
Fails to check if this API returns NULL.
https://github.com/microsoft/ebpf-for-windows/blob/c95a90219ecd4d68f071f469a2a9fda077630c9f/tests/end_to_end/end_to_end.cpp#L345

**Comment by dthaler** [comment]
Before assuming whether object__open can or cannot return success with 0 programs, please check what libbpf does and match the answer

**Comment by Alan-Jowett** [comment]
Might be related to #1649 as this can cause bpf_object__open to ignore OOM failure.

**Comment by saxena-anurag** [comment]
It looks like libbpf allows `bpf_object__open` to succeed with 0 ebpf programs. But that should only happen only when the ELF file really does not contain any programs. In the test code, we may not really need to check against null as the test code knows that it cannot be null.

As Alan mentioned, it may be due to #1649. Should we close this and open if we see it again?

**Comment by saxena-anurag** [comment]
Closing as discussed in triage meeting.
