### ISSUE TITLE
Update "deploy-ebpf.ps1" to use MSI to deploy eBPF-For-Windows

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#2422]
eBPF should be installed via the MSI to ensure it's tested correctly.

**Comment by dthaler** [comment]
> @Alan-Jowett, as documented [here](https://github.com/microsoft/ebpf-for-windows/blob/main/docs/InstallEbpf.md#method-2-install-files-you-built-yourself) in the `InstallEbpf.md`, `deploy-ebpf.ps1` is designed to be used for manually provisioning a VM, as a second method/alternative other than using the MSI itself (which works without any script directly on the VM).

Note that the `-m` or `--msi` option to deploy-ebpf.ps1 "Copies MSI instead of individual files",

**Comment by gtrevi** [comment]
@Alan-Jowett the title and the description of this issue are mentioning two different topics, which should be already addressed:

- There's a PR #2953 for testing the MSI in the CI/CD.
- `deploy-ebpf.ps1` already has the option to deploy the MSI instead of the individual files.

And, as documented [here](https://github.com/microsoft/ebpf-for-windows/blob/main/docs/InstallEbpf.md#method-2-install-files-you-built-yourself) in the `InstallEbpf.md`, `deploy-ebpf.ps1` is designed to be used for manually provisioning a VM (so not used in the CI/CD).

Therefore, with PR #2953, all should be addressed.

**Comment by dthaler** [comment]
> Therefore, with PR #2953, all should be addressed.

Disagree.  Today, any time we add a file we have to update both the MSI and the deploy script, and people often forget to update the deploy script.  I believe the individual-files functionality of the deploy script could be removed to make the project more maintainable.
