### ISSUE TITLE
CI/CD runs on release branches are de-prioritized.

### ISSUE THREAD

**Issue by gtrevi** [microsoft/ebpf-for-windows#3031]
Currently, if a CI/CD run is triggered on a `release/X.Y` branch, it will be cancelled if a "higher" priority CI/CD is triggered.

e.g.: https://github.com/microsoft/ebpf-for-windows/actions/runs/6803634465
```
Canceling since a higher priority waiting request for 'cicd-40822e69cd2acb3f86365ee2b60eeac907ffe8ea' exists
```

CI/CD runs on release branches should have the same priority of any other high priority request.

**Comment by rectified95** [comment]
Looks like something that can be controlled by the concurrency parameter in our cicd.yml:
https://stackoverflow.com/questions/69004608/cancel-previous-pipelines-when-a-new-one-is-triggered-github-actions

https://github.com/microsoft/ebpf-for-windows/blob/main/.github/workflows/cicd.yml#L26-L30

**Comment by rectified95** [comment]
The release run: https://github.com/microsoft/ebpf-for-windows/actions/runs/6803634465
got pre-empted by a merge queue one on main: https://github.com/microsoft/ebpf-for-windows/actions/runs/6803709846
because they they were both scheduled for the same commit: https://github.com/microsoft/ebpf-for-windows/commit/40822e69cd2acb3f86365ee2b60eeac907ffe8ea
as seen in their summary views.

I think the reverse would happen if the release branch workflow was run after the one on the main branch, since the concurrency group resolved to the same value - so this isn't a matter of release branches being lower priority.
