### ISSUE TITLE
Version number in source code on `main` not updated to v0.14.1.

### ISSUE THREAD

**Issue by gtrevi** [microsoft/ebpf-for-windows#3302]
`ReleaseProcess.md` specifies updating the source code on `main` with the latest release number. For the v0.14.1 this step was skipped (sources on `main` still on 0.14.0).

**Comment by saxena-anurag** [comment]
Since release of 0.14.1 required cherry-pick of some fixes from `main --> release\0.14` branch, and there were some more fixes in `main` present at that time that were not cherry-picked to the release branch, both the branches had effectively "diverged" in terms of the code base. In such a case, should we still be tagging main with `0.14.1`?

**Comment by gtrevi** [comment]
Yes, `main` should always be updated to the latest release version. Release branching diverging is absolutely normal.

**Comment by dahavey** [comment]
#3357
