### ISSUE TITLE
Bpf2c should embed the program info in native program instead of hash

### ISSUE THREAD

**Issue by shankarseal** [microsoft/ebpf-for-windows#3429]
Bpf2c should embed the program info in native program instead of hash. This will be useful in cases where the program info has flags fields. This was necessitated by https://github.com/microsoft/ebpf-for-windows/pull/3344 .

**Comment by Alan-Jowett** [comment]
The program information used to verify programs is hashed and the hash is written into the PE image. When loading a native image, the hash is compared with a hash of the current program information. If they don't match the program fails to load.

The issue is that when new fields are added, the hash will change even when the new field is not relevant to this specific instance of program information.

The proposal is to use the version information from the native image to compute a version specific hash of the current program information.

**Comment by dthaler** [comment]
If "the new field is not relevant" then it could be the same as a value of 0 in that field.
We could use a hash function that computes the same hash if there are trailing 0 bytes and then the hash would not change if irrelevant fields were added.

**Comment by shankarseal** [comment]
> The program information used to verify programs is hashed and the hash is written into the PE image. When loading a native image, the hash is compared with a hash of the current program information. If they don't match the program fails to load.
> 
> The issue is that when new fields are added, the hash will change even when the new field is not relevant to this specific instance of program information.
> 
> The proposal is to use the version information from the native image to compute a version specific hash of the current program information.

This may not work, as program info can be updated *without* change to the version number.
