### ISSUE TITLE
eBPF for Windows fails to build against newest WDK 26100

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#4016]
GitHub recently started pushing 26100 WDK, which breaks eBPF for Windows.

**Comment by shankarseal** [comment]
There is still a chance, While GH is rolling out the new VS tools in its runners, our CICD may get scheduled on a runner with older WDK and build may still fail.
A more robust solution would be to Install a nuget version of WDK instead of relying on the one installed in VS on the GH runner. This is tracked by #3844. WIP #4024.
