### ISSUE TITLE
Incremental linking makes debugging with windbg difficult

### ISSUE THREAD

**Issue by shankarseal** [microsoft/ebpf-for-windows#545]
Please remove incremental linking from all vcxproj.

**Comment by dthaler** [comment]
Can you elaborate on "difficult"?

**Comment by shankarseal** [comment]
e.g.

with ILT
call    ebpfapi!ILT+31180(?clear_map_descriptorsYAXXZ)

WIthout ILT
call    EbpfApi!clear_map_descriptors

The name mangling make it difficult to follow the when stepping through the code in windbg.

What is the dev/diagnostic benefit that of ILT that you are using?

**Comment by dthaler** [comment]
> e.g.
> 
> with ILT
> call ebpfapi!ILT+31180(?clear_map_descriptorsYAXXZ)
> 
> WIthout ILT
> call EbpfApi!clear_map_descriptors
> 
> The name mangling make it difficult to follow the when stepping through the code in windbg.

Sounds like your issue is with C++ name mangling rather than incremental linking per se (and offhand I have no idea why changing incremental linking would affect name mangling, do you know?).   As I suspect you are aware, [C++ name mangling](https://en.wikipedia.org/wiki/Name_mangling) is essential in dealing with cases where you have overloading of the same C++ function name with different prototypes.

There are at least two ways to deal with name mangling:
a) use extern "C" around prototypes,
b) use a debugger that is user-friendly.  If windbg isn't then we should ask windbg to improve their debugger, rather than asking every project in the world to change because of a specific debugger.

> What is the dev/diagnostic benefit that of ILT that you are using?

https://devblogs.microsoft.com/cppblog/the-visual-c-linker-best-practices-developer-iteration/

**Comment by shankarseal** [comment]
The 2 assemblies I copy pasted is compiling ebpfapi with/without incremental linking flag. The ILT prefix to each symbol stands for incremental link table. So the symbol names definitely change for this linker option. Note no code was changed to affect name mangling. Yes I am aware of C++ name mangling. But this seems different.

Incremental linking makes linking faster for small changes. Are you relying on this feature? If not, please approve the changes so that windbg experience gets simpler.

**Comment by Alan-Jowett** [comment]
Can you also please file a bug against WinDbg? If VS can handle it, why can't WinDbg?

**Comment by shankarseal** [comment]
I will follow up here https://github.com/microsoftfeedback/WinDbg-Feedback (Thanks Alan for the pointer.)

But meanwhile, I dont see a compelling reason why we need incremental linking? If we are not going to miss it, and removing it helps debugging experience, is there any reasons to not approve #546  ?
