### ISSUE TITLE
Add support for libbpf API compatibility

### ISSUE THREAD

**Issue by poornagmsft** [microsoft/ebpf-for-windows#84]
@saxena-anurag

**Comment by dthaler** [comment]
This is to expose literally the libbpf APIs, at least as .h file inline wrappers if not native.

**Comment by dthaler** [comment]
libbpf APIs have a permissive license so some of the code may be usable, even if not the code that wraps bpf() syscall.

**Comment by dthaler** [comment]
There are some issues currently in the libbpf code base, including:
1. Compiler specific, e.g., __attribute__ in code
2. OS-specific, e.g., include <linux/...> in code
3. Deprecated APIs like strdup instead of _strdup
4. Files with ambiguous license (no header at top)

**Comment by dthaler** [comment]
After much investigation, I've concluded that it would not currently make sense to try to use libbpf code directly, since libbpf hard-codes a list of prog types, helper func id names, etc., which lists can vary by platform.  So the current libbpf implementation is really Linux-specific even if the header file is platform agnostic.  At least in the short term, runtime implementations would be better off implementing their own platform-specific implementations of the common libbpf header.
