### ISSUE TITLE
run_driver_tests.psm1 falsely marks tests as passed when they fail

### ISSUE THREAD

**Issue by Alan-Jowett** [microsoft/ebpf-for-windows#998]
See as an example:
https://github.com/microsoft/ebpf-for-windows/runs/6134826890?check_suite_focus=true#step:9:118

**Comment by saxena-anurag** [comment]
This has been fixed in parts by multiple PRs:

https://github.com/microsoft/ebpf-for-windows/pull/1251/
https://github.com/microsoft/ebpf-for-windows/pull/1215
https://github.com/microsoft/ebpf-for-windows/pull/1213
https://github.com/microsoft/ebpf-for-windows/pull/1239
https://github.com/microsoft/ebpf-for-windows/pull/1242

Closing this issue.
